export const allSymptoms = [
    "Blood in urine पिसाबमा रगत",
    "Painful urination पिसाब गर्दा दुख्ने",
    "Frequent urination बारम्बार पिसाब लाग्ने",
    "Urinary incontinence पिसाब नरोकिने",
    "Kidney stones मृगौलाको पत्थरी",
    "Erectile dysfunction लिंग उठ्ने समस्या",
    "Testicular pain अण्डकोष दुख्ने",
    "Bladder pain मूत्राशय दुख्ने",
    "Difficulty starting urination पिसाब सुरु गर्न गाह्रो",
    "Urinary retention पिसाब नझर्ने",
    "Cloudy urine पिसाब पहेलो वा फोहोर देखिने",
    "Strong persistent urine odor पिसाबको बिरामी गन्ध",
    "Pelvic pain पेल्भिस दुख्ने",
    "Nocturia (frequent night urination) राति बारम्बार पिसाब लाग्ने",
    "Lower abdominal pain तल्लो पेट दुख्ने",
    "Burning sensation during urination पिसाब गर्दा जलन हुने",
    "Chest pain छाती दुख्ने",
    "Shortness of breath सास फुल्ने",
    "Palpitations हृदयको धड्कन बढी महसुस हुने",
    "Irregular heartbeat अनियमित हृदय धड्कन",
    "Swelling in legs/ankles खुट्टा सुन्निने वा सुज्ने",
    "Dizziness चक्कर आउने",
    "Fainting spells बेहोस हुने",
    "High blood pressure उच्च रक्तचाप",
    "Fatigue with exertion सानै काम गर्दा थकान हुने",
    "Pain radiating to left arm बाँया हतमा दुखाइ फैलिने",
    "Rapid weight gain तौल अचानक बढ्ने",
    "Cold sweats चिसो पसिना आउने",
    "Heartburn-like chest discomfort छातीमा जलन हुने",
    "Blue-tinged lips/fingers ओठ वा औंला निलो पर्ने",
    "Racing heartbeat हृदयको धड्कन छिटो हुने",
    "Chest tightness छाती कसेको महसुस हुने",
    "Headaches टाउको दुख्ने",
    "Numbness/tingling सुन्निएको वा चिटिक्क महसुस हुने",
    "Muscle weakness मांसपेशी कमजोर हुने",
    "Seizures दौरा पर्ने",
    "Memory problems स्मरण शक्ति कम हुने",
    "Vision changes दृष्टि समस्या",
    "Tremors हातखुट्टा काँड्ने",
    "Difficulty walking हिँड्न गाह्रो हुने",
    "Speech difficulties बोल्न गाह्रो हुने",
    "Loss of consciousness बेहोस हुने",
    "Chronic pain दीर्घकालीन दुखाइ",
    "Sleep disturbances निद्रामा समस्या",
    "Coordination problems समन्वयमा समस्या",
    "Migraines अर्धाशिशी (आधा टाउको दुख्ने)",
    "Balance problems सन्तुलन खोज्ने",
    "Joint pain जोर्नी दुख्ने",
    "Back pain पछाडि दुख्ने",
    "Swollen joints जोर्नी सुन्निने",
    "Limited range of motion जोर्नी चलाउन गाह्रो",
    "Bone fractures हड्डी भाँच्ने",
    "Muscle pain मांसपेशी दुख्ने",
    "Joint stiffness जोर्नी कडा हुने",
    "Sprains मोचिने",
    "Sports injuries खेलकुद चोट",
    "Neck pain घाँटी दुख्ने",
    "Knee/hip pain घुँडा वा नितम्ब दुख्ने",
    "Bone deformities हड्डी विकृति",
    "Difficulty moving limbs हातखुट्टा चलाउन गाह्रो",
    "Popping/clicking joints जोर्नीबाट आवाज आउने",
    "Shoulder pain काँध दुख्ने",
    "Arm/wrist pain बाहुली वा नारी दुख्ने",
    "Childhood fevers बच्चामा ज्वरो",
    "Developmental delays विकासमा ढिलाई",
    "Poor weight gain तौल नबढ्ने",
    "Behavioral issues व्यवहार समस्या",
    "Childhood vaccinations बच्चाको खोप",
    "Cough/cold in children बच्चामा खोकी/रूखो",
    "Ear infections बच्चामा कान संक्रमण",
    "Childhood asthma बच्चामा दम",
    "Rashes in children बच्चामा ददुरा",
    "Digestive issues in kids बच्चामा पाचन समस्या",
    "Growth concerns बच्चाको वृद्धि समस्या",
    "Learning difficulties सिक्ने समस्या",
    "Sleep problems in children बच्चामा निद्रा समस्या",
    "Adolescent health issues किशोरावस्था स्वास्थ्य समस्या",
    "Bedwetting बच्चाले बिहान भिजाउने",
    "Teething problems दाँत निस्कने समस्या",
    "Rashes ददुरा",
    "Acne एक्ने",
    "Eczema एक्जिमा",
    "Psoriasis सोरायसिस",
    "Skin discoloration छालाको रंग परिवर्तन",
    "Moles/changes तिलमा परिवर्तन",
    "Hair loss कपाल झर्ने",
    "Nail problems नङ समस्या",
    "Dry skin रुखो छाला",
    "Excessive sweating धेरै पसिना आउने",
    "Skin infections छाला संक्रमण",
    "Hives पित्ती उठ्ने",
    "Skin growths छालामा गाँठो",
    "Itchy skin खटलाग्दो छाला",
    "Sunburn घामले पोल्ने",
    "Warts मसिना",
    "Abdominal pain पेट दुख्ने",
    "Diarrhea पखाला",
    "Constipation दिसा नझर्ने",
    "Heartburn अम्लपित्त",
    "Bloating पेट फुल्ने",
    "Nausea मच्काउने",
    "Vomiting वान्ता हुने",
    "Rectal bleeding गुदाबाट रगत आउने",
    "Difficulty swallowing निल्न गाह्रो",
    "Weight loss तौल घट्ने",
    "Food intolerances खानेकुरा नबढ्ने",
    "Liver problems लिबर समस्या",
    "Gallbladder pain पित्ताशय दुख्ने",
    "Hemorrhoids बवासीर",
    "Changes in bowel habits दिसाको बानीमा परिवर्तन",
    "Acid reflux अम्ल फर्कने",
    "Cough खोकी",
    "Wheezing घरघराउने",
    "Chronic bronchitis दीर्घकालीन ब्रोंकाइटिस",
    "Asthma symptoms दमका लक्षणहरू",
    "COPD symptoms फोक्सोको दीर्घकालीन रोगका लक्षण",
    "Lung infections फोक्सो संक्रमण",
    "Coughing up blood खोकीमा रगत आउने",
    "Sleep apnea निद्रामा सास रोकिने",
    "Pulmonary fibrosis फोक्सो कडा हुने",
    "Allergic respiratory symptoms एलर्जीको सास फेर्ने समस्या",
    "Pneumonia न्युमोनिया",
    "Smoking-related lung issues धूम्रपानबाट फोक्सो समस्या",
    "Chronic cough दीर्घकालीन खोकी",
    "Chest congestion छाती भरिएको महसुस हुने",
    "Fatigue थकान",
    "Weight changes तौलमा परिवर्तन",
    "Diabetes symptoms मधुमेहका लक्षण",
    "Thyroid problems थाइराइड समस्याहरू",
    "Hormonal imbalances हर्मोन असन्तुलन",
    "Excessive thirst/urination धेरै पिसाब लाग्ने/धेरै तिर्खा लाग्ने",
    "Metabolic disorders मेटाबोलिक समस्या",
    "Osteoporosis हड्डी कमजोर हुने",
    "Adrenal problems एड्रिनल ग्रन्थिको समस्या",
    "Pituitary disorders पिट्यूटरी ग्रन्थिको विकार",
    "Growth disorders बढ्दो वा कम वृद्धि",
    "Menstrual irregularities महिनावारी अनियमितता",
    "Low testosterone टेस्टोस्टेरोन कम हुनु",
    "Cholesterol issues कोलेस्टेरोलको समस्या",
    "Heat/cold intolerance गर्मी/चिसो सहन नसक्ने",
    "Increased hunger बढी भोक लाग्ने",
    "Slow healing wounds घाउ ढिलो निको हुने",
    "Darkened skin patches छालामा कालो दागहरू",
    "Blurred vision धुमिलो दृष्टि",
    "Eye pain आँखामा दुखाइ",
    "Red eyes रातो आँखा",
    "Dry eyes सुक्खा आँखा",
    "Floaters/flashes आँखामा फ्लोटर/झिल्काहरू",
    "Double vision दोहोरो देखिने",
    "Vision loss दृष्टि हराउनु",
    "Cataract symptoms मोतीबिन्दुका लक्षण",
    "Glaucoma symptoms कालो मोतीबिन्दुका लक्षण",
    "Eye infections आँखा संक्रमण",
    "Light sensitivity प्रकाशप्रति संवेदनशीलता",
    "Difficulty seeing at night रातमा देख्न गाह्रो हुने",
    "Watery eyes आँखाबाट पानी आउने",
    "Eyelid problems पल्कामा समस्या",
    "Eye discharge आँखाबाट डिस्चार्ज",
    "Itchy eyes आँखा चिलाउने",
    "Swollen eyelids पल्का सुन्निने",
    "Eye fatigue आँखामा थकान",
    "Ear pain कान दुख्ने",
    "Hearing loss सुन्न नसक्ने",
    "Tinnitus कानमा आवाज गुँज्ने",
    "Sinus problems साइनसको समस्या",
    "Sore throat घाँटी दुख्ने",
    "Nasal congestion नाक बन्द हुने",
    "Vertigo घुमाउने महसुस हुने",
    "Tonsillitis टन्सिलको समस्या",
    "Voice changes आवाज परिवर्तन",
    "Swallowing difficulties निल्न गाह्रो हुने",
    "Nosebleeds नाकबाट रगत आउने",
    "Facial pain अनुहारमा दुखाइ",
    "Snoring/sleep apnea सुत्दाखेरि घुर्ने/सास रोकिने",
    "Head/neck masses टाउको/घाँटीमा गाँठो",
    "Ear drainage कानबाट पस वा पानी आउने",
    "Loss of smell गन्ध नआउने",
    "Hoarseness स्वर कर्कश हुने",
    "Ear fullness कान भरिएको महसुस",
    "Unexplained weight loss कारणबिना वजन घट्ने",
    "Persistent fatigue लगातार थकान",
    "Lumps/masses गाँठो वा मासु उम्रनु",
    "Unusual bleeding असामान्य रक्तश्राव",
    "Skin changes छालामा परिवर्तन",
    "Persistent pain लगातार दुखाइ",
    "Changes in bowel/bladder पिसाब/पाखाना सम्बन्धी परिवर्तन",
    "Nagging cough पुरानो खोकी",
    "White spots in mouth मुखमा सेता धब्बाहरू",
    "Unusual night sweats रातको समयमा अत्यधिक पसिना",
    "Fever of unknown origin अज्ञात ज्वरो",
    "Changes in moles तिल वा मोलमा परिवर्तन",
    "Persistent indigestion लगातार अपच",
    "Unhealing sores ननिको हुने घाउहरू",
    "Chronic headaches पुरानो टाउको दुखाइ",
    "Bone pain हड्डी दुख्ने",
    "Appetite loss भोक नलाग्ने",
    "Depression डिप्रेशन",
    "Anxiety चिन्ता",
    "Mood swings मूडमा उतार-चढाव",
    "Suicidal thoughts आत्महत्या सोच",
    "Panic attacks प्यानिक अट्याक",
    "Sleep disorders निन्द्रा समस्याहरू",
    "Eating disorders खानपानको समस्या",
    "Addiction issues लत लाग्ने समस्या",
    "Personality disorders व्यक्तित्वको विकार",
    "Psychotic symptoms मनोवैज्ञानिक लक्षणहरू",
    "OCD symptoms ओसीडी लक्षणहरू",
    "PTSD symptoms पीटीएसडी लक्षण",
    "ADHD symptoms एडीएचडी लक्षण",
    "Dementia symptoms डिमेन्सिया लक्षणहरू",
    "Irritability चिडचिडाहट",
    "Social withdrawal समाजिक रूपमा अलग हुने",
    "Hallucinations भ्रम देख्ने",
    "Impulsive behavior आकस्मिक व्यवहार",
    "Pelvic pain पेल्भिक दुखाइ",
    "Irregular periods अनियमित महिनावारी",
    "Painful periods महिनावारीको बेलामा दुखाइ",
    "Vaginal discharge योनिमा डिस्चार्ज",
    "Menopausal symptoms रजोनिवृत्तिका लक्षण",
    "Fertility issues बाँझोपन",
    "Pain during intercourse सम्भोगको बेला दुखाइ",
    "Breast concerns स्तन सम्बन्धी चिन्ता",
    "Pap smear needs प्याप स्मियरको आवश्यकता",
    "Vaginal bleeding योनिबाट रक्तश्राव",
    "Endometriosis symptoms एन्डोमेट्रियोसिसका लक्षणहरू",
    "PCOS symptoms पोलिसिस्टिक ओभरी सिन्ड्रोम",
    "STD concerns यौन संक्रामक रोगको शंका",
    "Missed periods महिनावारी रोकिने",
    "Heavy menstrual bleeding अत्यधिक महिनावारी",
    "Vaginal itching योनिमा चिलाउने",
    "Breast tenderness स्तन दुख्ने",
    "Appendicitis symptoms अपेन्डिसाइटिसका लक्षण",
    "Hernia symptoms हर्नियाका लक्षण",
    "Gallbladder symptoms पित्तथैलीको समस्या",
    "Acute abdominal pain तीव्र पेट दुखाइ",
    "Bowel obstruction आन्द्रा अवरुद्ध हुने",
    "Skin lesions needing removal छालाका गाठा हटाउन",
    "Breast lumps स्तनमा गाँठो",
    "Varicose veins शिरा फुल्ने समस्या",
    "Pilonidal cysts पाइलोनिडल सिस्ट",
    "Lipomas लिपोमा (चिल्लो गाठा)",
    "Surgical wound care शल्यक्रिया पछिको घाउको हेरचाह",
    "Trauma injuries आघात/चोटपटक",
    "Post-operative complications शल्यक्रिया पछिको जटिलता",
    "Non-healing wounds ननिको हुने घाउहरू",
    "Gangrene ग्याङ्ग्रिन (मांस मर्ने रोग)",
    "Abscesses घाउमा पस हुने",
    "Severe burns गम्भीर जलन"
  ];
  